" Vim color file - octagon
" Generated by http://bytefluent.com/vivify 2018-05-08
set background=dark
if version > 580
	hi clear
	if exists("syntax_on")
		syntax reset
	endif
endif

set t_Co=256
let g:colors_name = "octagon"

"hi CTagsMember -- no settings --
"hi CTagsGlobalConstant -- no settings --
hi Normal guifg=#e2e4e5 guibg=#282a3a guisp=#282a3a gui=NONE ctermfg=254 ctermbg=237 cterm=NONE
"hi CTagsImport -- no settings --
"hi CTagsGlobalVariable -- no settings --
"hi SpellRare -- no settings --
"hi EnumerationValue -- no settings --
"hi TabLineSel -- no settings --
"hi Union -- no settings --
"hi TabLineFill -- no settings --
"hi EnumerationName -- no settings --
"hi SpellCap -- no settings --
"hi SpellLocal -- no settings --
"hi DefinedName -- no settings --
"hi LocalVariable -- no settings --
"hi SpellBad -- no settings --
"hi CTagsClass -- no settings --
"hi TabLine -- no settings --
"hi clear -- no settings --
hi IncSearch guifg=#161821 guibg=#b2b9bd guisp=#b2b9bd gui=NONE ctermfg=234 ctermbg=250 cterm=NONE
hi WildMenu guifg=#66D9EF guibg=#000000 guisp=#000000 gui=NONE ctermfg=81 ctermbg=NONE cterm=NONE
hi SignColumn guifg=#A3E244 guibg=#232526 guisp=#232526 gui=NONE ctermfg=112 ctermbg=235 cterm=NONE
hi SpecialComment guifg=#465457 guibg=NONE guisp=NONE gui=bold ctermfg=240 ctermbg=NONE cterm=bold
hi Typedef guifg=#66D9EF guibg=NONE guisp=NONE gui=NONE ctermfg=81 ctermbg=NONE cterm=NONE
hi Title guifg=#fd951f guibg=NONE guisp=NONE gui=italic ctermfg=208 ctermbg=NONE cterm=NONE
hi Folded guifg=#465457 guibg=#000000 guisp=#000000 gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
hi PreCondit guifg=#A3E244 guibg=NONE guisp=NONE gui=bold ctermfg=112 ctermbg=NONE cterm=bold
hi Include guifg=#A3E244 guibg=NONE guisp=NONE gui=NONE ctermfg=112 ctermbg=NONE cterm=NONE
hi Float guifg=#c39ac9 guibg=NONE guisp=NONE gui=NONE ctermfg=141 ctermbg=NONE cterm=NONE
hi StatusLineNC guifg=#888d94 guibg=#1e1f2b guisp=#1e1f2b gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
hi NonText guifg=#888d94 guibg=#1e1f2b guisp=#1e1f2b gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
hi DiffText guifg=#e2e4e5 guibg=#545874 guisp=#545874 gui=bold,italic ctermfg=254 ctermbg=60 cterm=bold
hi ErrorMsg guifg=#c5556a guibg=#3a3d4b guisp=#3a3d4b gui=bold ctermfg=168 ctermbg=239 cterm=bold
hi Ignore guifg=#808080 guibg=#272822 guisp=#272822 gui=NONE ctermfg=8 ctermbg=235 cterm=NONE
hi Debug guifg=#BCA3A3 guibg=NONE guisp=NONE gui=bold ctermfg=138 ctermbg=NONE cterm=bold
hi PMenuSbar guifg=#3a3d4b guibg=#3a3d4b guisp=#3a3d4b gui=NONE ctermfg=239 ctermbg=239 cterm=NONE
hi Identifier guifg=#fd951f guibg=NONE guisp=NONE gui=NONE ctermfg=208 ctermbg=NONE cterm=NONE
hi SpecialChar guifg=#c5556a guibg=NONE guisp=NONE gui=bold ctermfg=197 ctermbg=NONE cterm=bold
hi Conditional guifg=#c5556a guibg=NONE guisp=NONE gui=bold ctermfg=168 ctermbg=NONE cterm=bold
hi StorageClass guifg=#FD971F guibg=NONE guisp=NONE gui=italic ctermfg=208 ctermbg=NONE cterm=NONE
hi Todo guifg=#FFFFFF guibg=#272822 guisp=#272822 gui=bold ctermfg=15 ctermbg=235 cterm=bold
hi Special guifg=#9cd1bb guibg=#282a3a guisp=#282a3a gui=bold,italic ctermfg=152 ctermbg=237 cterm=bold
hi LineNr guifg=#888d94 guibg=#1e1f2b guisp=#1e1f2b gui=NONE ctermfg=246 ctermbg=235 cterm=NONE
hi StatusLine guifg=#1e1f2b guibg=#888d94 guisp=#888d94 gui=NONE ctermfg=235 ctermbg=246 cterm=NONE
hi StatusLineTerm guifg=#1e1f2b guibg=#888d94 guisp=#888d94 gui=NONE ctermfg=235 ctermbg=246 cterm=NONE
hi StatusLineTermNC guifg=#1e1f2b guibg=#888d94 guisp=#888d94 gui=NONE ctermfg=235 ctermbg=246 cterm=NONE
hi Label guifg=#E6DB74 guibg=NONE guisp=NONE gui=NONE ctermfg=185 ctermbg=NONE cterm=NONE
hi PMenuSel guifg=#e2e4e5 guibg=#545874 guisp=#545874 gui=NONE ctermfg=254 ctermbg=60 cterm=NONE
hi Search guifg=#b2b9bd guibg=#161821 guisp=#161821 gui=NONE ctermfg=250 ctermbg=234 cterm=NONE
hi Delimiter guifg=#8F8F8F guibg=NONE guisp=NONE gui=NONE ctermfg=245 ctermbg=NONE cterm=NONE
hi Statement guifg=#c5556a guibg=NONE guisp=NONE gui=bold,italic ctermfg=168 ctermbg=NONE cterm=bold
hi Comment guifg=#888d94 guibg=NONE guisp=NONE gui=italic ctermfg=246 ctermbg=NONE cterm=NONE
hi Character guifg=#ffd400 guibg=NONE guisp=NONE gui=NONE ctermfg=185 ctermbg=NONE cterm=NONE
hi Number guifg=#c39ac9 guibg=NONE guisp=NONE gui=NONE ctermfg=182 ctermbg=NONE cterm=NONE
hi Boolean guifg=#c39ac9  guibg=NONE guisp=NONE gui=NONE ctermfg=141 ctermbg=NONE cterm=NONE
hi Operator guifg=#c5556a guibg=NONE guisp=NONE gui=NONE ctermfg=168 ctermbg=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#888d94 guisp=#888d94 gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
hi Question guifg=#9cd1bb guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi WarningMsg guifg=#c5556a guibg=#1e1f2b guisp=#1e1f2b gui=bold ctermfg=15 ctermbg=236 cterm=bold
hi VisualNOS guifg=#1e1f2b guibg=#b2b9bd guisp=#b2b9bd gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
hi DiffDelete guifg=#c5556a guibg=#3a3d4b guisp=#3a3d4b gui=NONE ctermfg=168 ctermbg=239 cterm=NONE
hi ModeMsg guifg=#ffd400 guibg=NONE guisp=NONE gui=NONE ctermfg=214 ctermbg=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#888D94 guisp=#888D94 gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE
hi Define guifg=#66D9EF guibg=NONE guisp=NONE gui=NONE ctermfg=81 ctermbg=NONE cterm=NONE
hi Function guifg=#a3e244 guibg=NONE guisp=NONE gui=NONE ctermfg=149 ctermbg=NONE cterm=NONE
hi FoldColumn guifg=#465457 guibg=#000000 guisp=#000000 gui=NONE ctermfg=240 ctermbg=NONE cterm=NONE
hi PreProc guifg=#A3E244 guibg=NONE guisp=NONE gui=NONE ctermfg=112 ctermbg=NONE cterm=NONE
hi Visual guifg=#1e1f2b guibg=#b2b9bd guisp=#b2b9bd gui=NONE ctermfg=NONE ctermbg=238 cterm=NONE
hi MoreMsg guifg=#ffd400 guibg=NONE guisp=NONE gui=NONE ctermfg=185 ctermbg=NONE cterm=NONE
hi VertSplit guifg=#888d94 guibg=#1e1f2b guisp=#1e1f2b gui=bold ctermfg=246 ctermbg=235 cterm=bold
hi Exception guifg=#A3E244 guibg=NONE guisp=NONE gui=bold ctermfg=112 ctermbg=NONE cterm=bold
hi Keyword guifg=#fd951f guibg=NONE guisp=NONE gui=bold,italic ctermfg=208 ctermbg=NONE cterm=bold
hi Type guifg=#9cd1bb guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi DiffChange guifg=#e2e4e5 guibg=#43465e guisp=#43465e gui=NONE ctermfg=60 ctermbg=60 cterm=NONE
hi Cursor guifg=#1e1f2b guibg=#b2b9bd guisp=#b2b9bd gui=NONE ctermfg=NONE ctermbg=230 cterm=NONE
hi Error guifg=#960050 guibg=#1E0010 guisp=#1E0010 gui=NONE ctermfg=89 ctermbg=53 cterm=NONE
hi PMenu guifg=#f8f8f2 guibg=#43465e guisp=#43465e gui=NONE ctermfg=230 ctermbg=60 cterm=NONE
hi SpecialKey guifg=#66D9EF guibg=NONE guisp=NONE gui=italic ctermfg=81 ctermbg=NONE cterm=NONE
hi Constant guifg=#c39ac9 guibg=NONE guisp=NONE gui=bold ctermfg=182 ctermbg=NONE cterm=bold
hi Tag guifg=#c5556a guibg=NONE guisp=NONE gui=italic ctermfg=197 ctermbg=NONE cterm=NONE
hi String guifg=#ffd400 guibg=NONE guisp=NONE gui=NONE ctermfg=214 ctermbg=NONE cterm=NONE
hi PMenuThumb guifg=#545874 guibg=#545874 guisp=#545874 gui=NONE ctermfg=60 ctermbg=60 cterm=NONE
hi MatchParen guifg=#1e1f2b guibg=#FD971F guisp=#FD971F gui=bold ctermfg=NONE ctermbg=208 cterm=bold
hi Repeat guifg=#c5556a guibg=NONE guisp=NONE gui=bold ctermfg=197 ctermbg=NONE cterm=bold
hi Directory guifg=#A3e244 guibg=NONE guisp=NONE gui=bold ctermfg=112 ctermbg=NONE cterm=bold
hi Structure guifg=#66D9EF guibg=NONE guisp=NONE gui=NONE ctermfg=81 ctermbg=NONE cterm=NONE
hi Macro guifg=#C4BE89 guibg=NONE guisp=NONE gui=italic ctermfg=186 ctermbg=NONE cterm=NONE
hi Underlined guifg=#808080 guibg=NONE guisp=NONE gui=underline ctermfg=8 ctermbg=NONE cterm=underline
hi DiffAdd guifg=#e2e4e5 guibg=#3a3d4b guisp=#3a3d4b gui=NONE ctermfg=254 ctermbg=239 cterm=NONE
hi cursorim guifg=#1e1f2b guibg=#b2b9bd guisp=#b2b9bd  gui=NONE ctermfg=235 ctermbg=60 cterm=NONE
